import type { Metadata } from "next";
import Head  from "next/head";
import { Inter } from "next/font/google";
import 'bulma/css/bulma.min.css';
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Myles is the best!🫀",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Head>
        <title>Myles is the best!🫀</title> {/* He truly is */}
        <link
          rel="stylesheet"
          href="https://jenil.github.io/bulmaswatch/yeti/bulmaswatch.min.css"
        />
      </Head>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
